city_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/CityController.php"
    type: annotation
    prefix:   /cidade
city_backend:
    resource: "@ReurbanoCoreBundle/Controller/Backend/CityController.php"
    type: annotation
    prefix:   /admin/cidade