core_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/CoreController.php"
    type: annotation
city_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/CityController.php"
    type: annotation
mailing_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/MailingController.php"
    type: annotation
    prefix:   /mailing
mailing_backend:
    resource: "@ReurbanoCoreBundle/Controller/Backend/MailingController.php"
    type: annotation
    prefix:   admin/mailing
banner_backend:
    resource: "@ReurbanoCoreBundle/Controller/Backend/BannerController.php"
    type: annotation
    prefix:   admin/banner
city_backend:
    resource: "@ReurbanoCoreBundle/Controller/Backend/CityController.php"
    type: annotation
    prefix:   /admin/cidade
html_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/HtmlController.php"
    type: annotation
    prefix:   /conteudo