city_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/CityController.php"
    type: annotation
    prefix:   /cidade
mailing_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/MailingController.php"
    type: annotation
    prefix:   /mailing
city_backend:
    resource: "@ReurbanoCoreBundle/Controller/Backend/CityController.php"
    type: annotation
    prefix:   /admin/cidade
html_frontend:
    resource: "@ReurbanoCoreBundle/Controller/Frontend/HtmlController.php"
    type: annotation
    prefix:   /conteudo