imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret: %secret%
    charset: UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ['twig'], assets_version: v1.3}
    default_locale: %locale%
    session:
        auto_start: true
    translator: { fallback: en }

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    read_from:      %themes_dir%
    write_to: %kernel.root_dir%/../web
    use_controller: false
#    assets:
#        teste: css/text.css
#        testejs: css/text.css
    filters:
        cssrewrite: ~
        sass:
            apply_to: "\.sass$"
        yui_css:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar
        yui_js:
            jar: %kernel.root_dir%/java/yuicompressor-2.4.6.jar
#    twig:
#        functions:
#            yui_css: { output: css/*.css }
#    filters:
#        cssrewrite: ~
        # closure:
        # jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        # jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: %mongo_server_prod%
            options:
                connect: true
        crawler:
            server: %mongo_server_prod%
            options:
                connect: true
    default_database: %mongo_database%_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
            mappings:
                StofDoctrineExtensionsBundle: false
            metadata_cache_driver: apc # array, apc, xcache, memcache
        crawler:
            connection: crawler
            database: %mongo_database_crawler%_prod
            auto_mapping: true
            mappings:
                StofDoctrineExtensionsBundle: false
            metadata_cache_driver: apc # array, apc, xcache, memcache

stof_doctrine_extensions:
    default_locale: pt_BR
    mongodb:
        default: 
            sluggable: true
        
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
# Para usar a linha abaixo, é preciso adicionar "app/console swiftmailer:spool:send --time-limit=10" ao Cron
#    spool:
#        type: file
#        path: %kernel.root_dir%/spool

jms_security_extra:
    secure_all_services: false
    enable_iddqd_attribute: false
    
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [ReurbanoUserBundle, ReurbanoOrderbundle]
        directories: [%kernel.root_dir%/../src]

mastop_system:
    themes_dir: %themes_dir%
    active_theme: "reurbano"
    twitter:
       file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
       consumer_key: gfOuKj8MmG8Wc2wGyGyDCg
       consumer_secret: rJCedVjsmmnED4ZLgHiyUPNNBQ6vtTzkObarciVhs
       callback_url: http://www.reurbano.com.br/usuario/twitter/back

reurbano_core:
    default_city: "oferta-nacional"
    quova:
      apikey: "200.1.MDAxODAwMDAwMHM0UzVQQUFV.MDAxODAwMDAwMHM0UzVQQUFV.rAS8PTJOuQYZ1g5QzZ4H94L4fIkXFfEC"
      secret: "nhmR2vdE"
      
services:
  text.twig.extension:
    class: Twig_Extensions_Extension_Text
    tags:
      -  { name: twig.extension } 
