parameters:
  mongo_server: mongodb://localhost:27017
  mongo_server_prod: mongodb://10.76.197.134:27017
  mongo_database: reurbano
  mongo_database_crawler: bancooferta

  mailer_transport: mail
  mailer_host: localhost
  mailer_user: null
  mailer_password: null 

  locale: pt_BR

  secret: MastopInternetDevelopment_OhMyGodThisIsSoSecret
  secretRemember: MastopInternetDevelopment_OhGoshThisIsSOSecret

  themes_dir: %kernel.root_dir%/../src/Reurbano/CoreBundle/Resources/views/themes