ReurbanoCoreBundle:
    resource: "@ReurbanoCoreBundle/Resources/config/routing/routing.yml"
ReurbanoDealBundle:
    resource: "@ReurbanoDealBundle/Resources/config/routing/routing.yml"
mastop_system:
  resource: "@MastopSystemBundle/Resources/config/routing/routing.yml"

mastop_teste:
    resource: "@MastopTesteBundle/Resources/config/routing/teste.yml"
    prefix:   /teste

#_welcome:
#    pattern:  /
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }
#
# Internal routing configuration to handle ESI
#_internal:
# resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
# prefix: /_internal