_home:
    pattern:  /
    defaults: { _controller: MastopSystemBundle:Home:index }
    
_teste:
    resource: "@MastopTesteBundle/Controller/TesteController.php"
    type: annotation
    prefix:   /teste

#_welcome:
#    pattern:  /
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }
#
_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo