ReurbanoCoreBundle:
    resource: "@ReurbanoCoreBundle/Resources/config/routing/routing.yml"
ReurbanoDealBundle:
    resource: "@ReurbanoDealBundle/Resources/config/routing/routing.yml"
MastopSystemBundle:
  resource: "@MastopSystemBundle/Resources/config/routing/routing.yml"

MastopTesteBundle:
    resource: "@MastopTesteBundle/Resources/config/routing/teste.yml"
    prefix:   /teste

ReurbanoUserBundle:
   resource:  "@ReurbanoUserBundle/Resources/config/routing.yml"
   prefix:   /usuario
   
userBackend:
   resource:  "@ReurbanoUserBundle/Resources/config/routingBackend.yml"
   prefix:   /admin/usuario
   
login:
    resource: "@ReurbanoUserBundle/Controller/Frontend/SecurityController.php"
    type:     annotation
    prefix:   /login
login_check:
    pattern:   /login_check

