mastop_system:
  resource: "@MastopSystemBundle/Resources/config/routing/routing.yml"

mastop_teste:
    resource: "@MastopTesteBundle/Resources/config/routing/teste.yml"
    prefix:   /teste

#_welcome:
#    pattern:  /
#    defaults: { _controller: AcmeDemoBundle:Welcome:index }
#
_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
    
user:
   resource:  "@MastopUserBundle/Resources/config/routing.yml"
   prefix:   /usuario
   
userBackend:
   resource:  "@MastopUserBundle/Resources/config/routingBackend.yml"
   prefix:   /admin/usuario
   
login:
    resource: "@MastopUserBundle/Controller/Frontend/SecurityController.php"
    type:     annotation
    prefix:   /login
login_check:
    pattern:   /login_check