services:
    mastop.user:
        class: Reurbano\UserBundle\Security\DocumentUserProvider
        arguments: [@mastop.dm, Reurbano\UserBundle\Document\User]
    mastop.user.success_handler:
        class: Reurbano\UserBundle\Security\SuccessHandler
        arguments: [@router]
    mastop.user.security.interactive_login_listener:
        class: Reurbano\UserBundle\Security\InteractiveLoginListener
        arguments: [@mastop.user, @service_container]
        tags:
          - {name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}
    

security:
    encoders:
        Reurbano\UserBundle\Document\User: sha512
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
#            entity: { class: Symfony\Bundle\DoctrineMongoDBBundle\Security\DocumentUserProvider, property: email }
             id: mastop.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: mastop.user.success_handler
                remember_me: true
                username_parameter: _umail
            remember_me:
                key:      %secretRemember%
                lifetime: 3600
                path:     /
                domain:   ~
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https}
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
