order_frontend:
    resource: "@ReurbanoOrderBundle/Controller/Frontend/OrderController.php"
    type: annotation
order_checkout_frontend:
    resource: "@ReurbanoOrderBundle/Controller/Frontend/CheckoutController.php"
    type: annotation
    prefix:   /minha-conta/financeiro
order_myorders_frontend:
    resource: "@ReurbanoOrderBundle/Controller/Frontend/MyOrdersController.php"
    type: annotation
    prefix:   /minha-conta/compras
order_mysales_frontend:
    resource: "@ReurbanoOrderBundle/Controller/Frontend/MySalesController.php"
    type: annotation
    prefix:   /minha-conta/vendas
order_backend:
    resource: "@ReurbanoOrderBundle/Controller/Backend/OrderController.php"
    type: annotation
    prefix:   /admin/vendas
order_status_backend:
    resource: "@ReurbanoOrderBundle/Controller/Backend/StatusController.php"
    type: annotation
    prefix:   /admin/vendas/status
order_checkout_backend:
    resource: "@ReurbanoOrderBundle/Controller/Backend/CheckoutController.php"
    type: annotation
    prefix:   /admin/vendas/resgates
order_refund_backend:
    resource: "@ReurbanoOrderBundle/Controller/Backend/RefundController.php"
    type: annotation
    prefix:   /admin/vendas/reembolsos