#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', ''));

$kernel = new AppKernel($env, $debug);
// Arruma requestcontext
$kernel->boot();
$requestCtx = $kernel->getContainer()->get('router')->getContext();
$requestCtx->setHost($kernel->getContainer()->getParameter('site_host'));
//$requestCtx->setBaseUrl('/mybaseurl');
//$requestCtx->setScheme('https');
// Fim 
$application = new Application($kernel);
$application->run();
