tracking_backend:
    resource: "@ReurbanoAnalyticsBundle/Controller/Backend/TrackingController.php"
    type: annotation
    prefix:   admin/rastreamento
tracking_pre_sell_backend:
    resource: "@ReurbanoAnalyticsBundle/Controller/Backend/TrackingPreSellController.php"
    type: annotation
    prefix:   admin/rastreamento/pre-venda
tracking_sell_backend:
    resource: "@ReurbanoAnalyticsBundle/Controller/Backend/TrackingSellController.php"
    type: annotation
    prefix:   admin/rastreamento/venda